### ISSUE TITLE
小爱课程表如何进入教务系统导入课程

### ISSUE THREAD

**Issue by cxOrz** [xwwwb/zzuli_course_xiaoai#1]
如图，找不到搜不到教务系统怎麽办 :crying_cat_face: 

![Screenshot_20220906-162503_小爱课程表](https://user-images.githubusercontent.com/32982052/188585412-4c927a6e-aa5e-4785-8d61-d81d814bbede.png)

**Comment by xwwwb** [comment]
向下翻有个图标叫 课程信息 不过暂时导入不了，因为学校没有把课程信息导入到i轻工大 等学校导入之后才能使用

**Comment by cxOrz** [comment]
好滴
